name: dir_contents_diff
environment:
  sdk: '>=3.2.0-0 <4.0.0'
dev_dependencies:
  litetest: any
  path: any
dependency_overrides:
  async_helper:
    path: ../../third_party/dart/pkg/async_helper
  expect:
    path: ../../third_party/dart/pkg/expect
  litetest:
    path: ../../testing/litetest
  meta:
    path: ../../third_party/dart/pkg/meta
  path:
    path: ../../third_party/dart/third_party/pkg/path
  smith:
    path: ../../third_party/dart/pkg/smith
